#!/bin/bash

mkdir -p example
cat > example/example.fa <<EOF
>chr1
TCGCTGCTGTCGGACTCCTAGTTACGTGGCGTTGCTCCACAGGTAGCCTGCCGTCGTGGTCCGCAACACT
CGCACGCTGTTTCAGGGCGATCCTCCGGATAACACCACCTCCACAAACGAAGACAACCCTCTGGTTCTTT
CCCGTCCGTAAGACTACTTATGAGGCCATACCAGGGTCGTTTGCAAAGTCAATAGCAGCCATAGTCCAAC
TTTCCGGGTATTGGCCGCTTGGCTAGTCGTCGGCACTGGCTGCTGATACATGCAGAGCTCCTGATAAGCT
ACCCGCTACGTGGCAGTCGCGCCTCCCCGAATTATCGGTGGTTAGCTTGTGCAGCCTTGACATAGAATTC
CGGTGACTCGGGGACGGGCAGAGGCCGTACATGTATCCCGATGTCAGTGATTCCATTTTTCATAGAGGAG
TTGTTGAACTCCCAAGAAGCCCGACAGGAGCAGGATTCACGGATCGTACCGAATAACAACTCCCTTATTG
CCGCCTACGT
EOF
cat > example/reads.fq <<EOF
@read1
GTTGCTCCACAGGTAGCCTGCCGTCGTGGTCCGCAACACTCGCACGCTGTGTCAGGGCGATCCTCCGGATAACACCACCTCCACAAACGAAGACAACCCT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@read2
GCGACTGCCACGTAGCGGGTAGCTTATCAGGAGCTCTGCATGTATCAGCTGCCAGTGCCGACGACTAGCCAAGCGGCCAATACCCGGAAAGTTGGACTAT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@read3
ATGTATCCCGATGTCAGTGATTCCATTTTTCATAGAGGAGTTGTTGAACTTCCAAGAAGCCCGACAGGAGCAGGATTCACGGATCGTACCGAATAACAAC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
EOF

WASM_FLAGS="$EM_FLAGS --preload-file example@/bwa/"

# Compile with SIMD
# Need "-DHAVE_PTHREAD" otherwise outputs valid SAM header but no alignments
echo "Compiling with SIMD"
emmake make \
	CC=emcc \
	AR=emar \
	PROG=../build/bwa-simd.js \
	CFLAGS="-Wall -Wno-unused-function -O3 -msse2 -msimd128" \
	DFLAGS="-DHAVE_PTHREAD" \
	LIBS="-lm -s USE_ZLIB=1 $WASM_FLAGS -msimd128"

# Compile without SIMD: ksw.c falls back to bwa's own scalar_sse.h emulation
echo "Compiling without SIMD"
make clean
emmake make \
	CC=emcc \
	AR=emar \
	PROG=../build/bwa.js \
	CFLAGS="-Wall -Wno-unused-function -O3" \
	DFLAGS="-DHAVE_PTHREAD" \
	LIBS="-lm -s USE_ZLIB=1 $WASM_FLAGS"
