FROM emscripten/emsdk:6.0.3 AS wasm-builder-emscripten6

RUN apt-get update && apt-get install -y \
    autoconf automake libtool pkg-config \
    liblzma-dev libbz2-dev libpng-dev zlib1g-dev default-libmysqlclient-dev \
    rsync wget

COPY ./bin/test_server.py /usr/src/

EXPOSE 80
CMD ["python3", "/usr/src/test_server.py"]