import { getAssetFromKV, mapRequestToAsset } from "@cloudflare/kv-asset-handler";

// Settings
const URL_CDN = "cdn/v3";
const CACHE_CONFIG = {
	browserTTL: 604800,  // 1 week (default: null)
	edgeTTL: 172800,     // 2 days (default: 2 days)
	bypassCache: false   // Do not bypass Cloudflare's cache (default: false)
};

// Routes (generated by biowasm deploy script)
const ASSET_MANIFEST = {
	"cdn/v3/samtools/1.10/samtools.js": "test123"
};

// GET /cdn/v3/:tool/:version/:file
export async function GET({ request, platform }) {
	console.log("platform =", platform);

	let response = await getAssetFromKV({
		request,
		waitUntil: promise => platform.context.waitUntil(promise)
	},
	{
		ASSET_MANIFEST,
		ASSET_NAMESPACE: platform.env.CDN,
		cacheControl: CACHE_CONFIG,
		// mapRequestToAsset: request => {
		// 	let url = request.url
		// 	url = url.replace("/docs", "").replace(/^\/+/, "")
		// 	return mapRequestToAsset(new Request(url, request))
		// },
	});

	// Enable CORS
	response.headers.set("Access-Control-Allow-Origin", "*");
	return response;
}
